<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <FileAlignment>4096</FileAlignment>
    <EmbedAllSources>true</EmbedAllSources>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <FileAlignment>4096</FileAlignment>
    <EmbedAllSources>true</EmbedAllSources>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft-WindowsAPICodePack-Core" Version="1.1.5" />
    <PackageReference Include="Microsoft-WindowsAPICodePack-Shell" Version="1.1.5" />
    <PackageReference Include="NLog" Version="6.0.3" />
    <PackageReference Include="NLog.Extensions.Hosting" Version="6.0.3" />
    <PackageReference Include="NLog.Extensions.Logging" Version="6.0.3" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Helper\Impl\" />
    <Folder Include="Helper\Interface\" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="if &quot;$(Configuration)&quot; == &quot;Release&quot; (&#xD;&#xA;   xcopy /Y /I &quot;$(TargetDir)&quot; &quot;%25USERPROFILE%25\Documents\SelfMadeDLL\WPFCommonLibrary\&quot;&#xD;&#xA;)" />
  </Target>

</Project>
